AllCops:
  DisplayCopNames: true
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
Metrics/CyclomaticComplexity:
  Max: 8
Style/FileName:
  Exclude: [Gemfile*]
Metrics/ModuleLength:
  Enabled: false
