AllCops:
  TargetRubyVersion: 2.5 # Oldest version kubeclient supports
  NewCops: enable
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Layout/LineLength:
  Max: 100
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ModuleLength:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods: [require, raise, include, attr_reader, refute, assert, require_relative]
  Exclude: [Gemfile, Rakefile, kubeclient.gemspec, Gemfile.dev.rb]
Metrics/BlockLength:
  Exclude: [kubeclient.gemspec]
Security/MarshalLoad:
  Exclude: [test/**/*]
Naming/FileName:
  Exclude: [Gemfile, Rakefile, Gemfile.dev.rb]
Style/RegexpLiteral:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Gemspec/OrderedDependencies:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/AccessorGrouping:
  EnforcedStyle: separated
Style/NegatedIfElseCondition:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
